-- ============================================================================
-- schema.sql — โครงสร้างฐานข้อมูล (PostgreSQL) ของระบบจัดการพอร์ตการลงทุน
--
-- ใช้ตอนไหน
--   - โปรไฟล์ prod: Spring รันไฟล์นี้ก่อน แล้ว Hibernate ตรวจว่า entity ตรงกับตาราง (ddl-auto: validate)
--   - โปรไฟล์ dev: Hibernate สร้าง/อัปเดตตารางเอง (ddl-auto: update) ไฟล์นี้จึงไม่ถูกรัน
-- รันซ้ำได้ทุกครั้งที่ start: ทุกคำสั่งใช้ IF NOT EXISTS
--
-- หลักการตั้งชื่อ
--   pk_<ตาราง>, fk_<ตาราง>_<คอลัมน์>, uq_<ตาราง>_<คอลัมน์>, ck_<ตาราง>_<เงื่อนไข>, idx_<ตาราง>_<คอลัมน์>
--
-- นโยบายเมื่อลบข้อมูลแม่ (ON DELETE)
--   CASCADE  = ข้อมูลลูกไม่มีความหมายถ้าไม่มีแม่ (โปรไฟล์ของผู้ใช้, ข้อมูลทั้งหมดในพอร์ต, ราคาของสินทรัพย์)
--              สอดคล้องกับ cascade = ALL + orphanRemoval ฝั่ง JPA
--   RESTRICT = ห้ามลบสินทรัพย์ที่ยังถูกใช้ในพอร์ต/ธุรกรรม/alert/เป้าหมาย เพราะเป็นประวัติทางการเงิน
-- ============================================================================

-- ---------- users : บัญชีผู้ใช้ ----------
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(50)  NOT NULL,
    email         VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

-- ---------- user_profiles : ข้อมูลเพิ่มเติมของผู้ใช้ (1:1 กับ users) ----------
CREATE TABLE IF NOT EXISTS user_profiles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT       NOT NULL,
    risk_tolerance  VARCHAR(20),
    investment_goal VARCHAR(255),
    phone           VARCHAR(20),
    CONSTRAINT pk_user_profiles PRIMARY KEY (id),
    -- UNIQUE บน FK คือสิ่งที่ทำให้เป็น 1:1 (ผู้ใช้หนึ่งคนมีโปรไฟล์ได้แถวเดียว)
    CONSTRAINT uq_user_profiles_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_profiles_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_profiles_risk CHECK (risk_tolerance IS NULL OR risk_tolerance IN ('LOW', 'MEDIUM', 'HIGH'))
);

-- ---------- assets : สินทรัพย์ที่ซื้อขายได้ (หุ้น, ETF, คริปโต ฯลฯ) ----------
CREATE TABLE IF NOT EXISTS assets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    symbol       VARCHAR(20)  NOT NULL,
    name         VARCHAR(100) NOT NULL,
    asset_type   VARCHAR(20)  NOT NULL,
    exchange     VARCHAR(50),
    price_source VARCHAR(20),
    CONSTRAINT pk_assets PRIMARY KEY (id),
    CONSTRAINT uq_assets_symbol UNIQUE (symbol),
    CONSTRAINT ck_assets_type CHECK (asset_type IN ('STOCK', 'ETF', 'BOND', 'MUTUAL_FUND', 'CRYPTO', 'CASH')),
    CONSTRAINT ck_assets_price_source CHECK (price_source IS NULL OR price_source IN ('YAHOO', 'SYNTHETIC'))
);

-- ---------- market_indices : ดัชนีตลาดสำหรับเปรียบเทียบผลตอบแทน ----------
CREATE TABLE IF NOT EXISTS market_indices (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    index_code VARCHAR(20)  NOT NULL,
    name       VARCHAR(100) NOT NULL,
    CONSTRAINT pk_market_indices PRIMARY KEY (id),
    CONSTRAINT uq_market_indices_code UNIQUE (index_code)
);

-- ---------- portfolios : พอร์ตการลงทุน (N:1 กับ users) ----------
CREATE TABLE IF NOT EXISTS portfolios (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT       NOT NULL,
    name          VARCHAR(100) NOT NULL,
    base_currency VARCHAR(10)  NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_portfolios PRIMARY KEY (id),
    CONSTRAINT fk_portfolios_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_portfolios_user_id ON portfolios (user_id);

-- ---------- holdings : สินทรัพย์ที่ถืออยู่ในพอร์ต (ตารางเชื่อม N:M portfolios <-> assets ที่มีข้อมูลของตัวเอง) ----------
CREATE TABLE IF NOT EXISTS holdings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id BIGINT         NOT NULL,
    asset_id     BIGINT         NOT NULL,
    quantity     NUMERIC(18, 6) NOT NULL,
    avg_cost     NUMERIC(18, 4) NOT NULL,
    updated_at   TIMESTAMP(6)   NOT NULL,
    CONSTRAINT pk_holdings PRIMARY KEY (id),
    -- พอร์ตหนึ่งถือสินทรัพย์ตัวเดียวกันได้แถวเดียว (index นี้ใช้ค้นตาม portfolio_id ได้ด้วย เพราะเป็นคอลัมน์แรก)
    CONSTRAINT uq_holdings_portfolio_asset UNIQUE (portfolio_id, asset_id),
    CONSTRAINT fk_holdings_portfolio_id FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT fk_holdings_asset_id FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE RESTRICT,
    CONSTRAINT ck_holdings_quantity CHECK (quantity >= 0),
    CONSTRAINT ck_holdings_avg_cost CHECK (avg_cost >= 0)
);
CREATE INDEX IF NOT EXISTS idx_holdings_asset_id ON holdings (asset_id);

-- ---------- transactions : ประวัติซื้อ/ขาย/ปันผล (N:1 กับ portfolios และ assets) ----------
CREATE TABLE IF NOT EXISTS transactions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id BIGINT         NOT NULL,
    asset_id     BIGINT         NOT NULL,
    type         VARCHAR(20)    NOT NULL,
    quantity     NUMERIC(18, 6) NOT NULL,
    price        NUMERIC(18, 4) NOT NULL,
    executed_at  TIMESTAMP(6)   NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id),
    CONSTRAINT fk_transactions_portfolio_id FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT fk_transactions_asset_id FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE RESTRICT,
    CONSTRAINT ck_transactions_type CHECK (type IN ('BUY', 'SELL', 'DIVIDEND', 'DEPOSIT', 'WITHDRAWAL')),
    CONSTRAINT ck_transactions_quantity CHECK (quantity > 0),
    CONSTRAINT ck_transactions_price CHECK (price > 0)
);
-- ดูประวัติของพอร์ต และคำนวณผลตอบแทนตามช่วงเวลา (portfolio_id + executed_at)
CREATE INDEX IF NOT EXISTS idx_transactions_portfolio_executed ON transactions (portfolio_id, executed_at);
CREATE INDEX IF NOT EXISTS idx_transactions_asset_id ON transactions (asset_id);

-- ---------- price_history : ราคารายวันของสินทรัพย์ (N:1 กับ assets) ----------
CREATE TABLE IF NOT EXISTS price_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset_id   BIGINT         NOT NULL,
    price_date DATE           NOT NULL,
    open       NUMERIC(18, 4) NOT NULL,
    high       NUMERIC(18, 4) NOT NULL,
    low        NUMERIC(18, 4) NOT NULL,
    close      NUMERIC(18, 4) NOT NULL,
    volume     BIGINT,
    CONSTRAINT pk_price_history PRIMARY KEY (id),
    -- หนึ่งสินทรัพย์มีราคาได้วันละแถว และเป็น index หลักของการค้นราคาตามช่วงวันที่
    CONSTRAINT uq_price_history_asset_date UNIQUE (asset_id, price_date),
    CONSTRAINT fk_price_history_asset_id FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE,
    CONSTRAINT ck_price_history_positive CHECK (open > 0 AND high > 0 AND low > 0 AND close > 0),
    CONSTRAINT ck_price_history_range CHECK (high >= low)
);

-- ---------- index_price_history : ค่าดัชนีรายวัน (N:1 กับ market_indices) ----------
CREATE TABLE IF NOT EXISTS index_price_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    market_index_id BIGINT         NOT NULL,
    price_date      DATE           NOT NULL,
    close_value     NUMERIC(18, 4) NOT NULL,
    CONSTRAINT pk_index_price_history PRIMARY KEY (id),
    CONSTRAINT uq_index_price_history_index_date UNIQUE (market_index_id, price_date),
    CONSTRAINT fk_index_price_history_market_index_id FOREIGN KEY (market_index_id) REFERENCES market_indices (id) ON DELETE CASCADE,
    CONSTRAINT ck_index_price_history_close CHECK (close_value > 0)
);

-- ---------- price_alerts : การแจ้งเตือนราคา (N:1 กับ portfolios และ assets) ----------
CREATE TABLE IF NOT EXISTS price_alerts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id BIGINT         NOT NULL,
    asset_id     BIGINT         NOT NULL,
    condition    VARCHAR(20)    NOT NULL,
    target_price NUMERIC(18, 4) NOT NULL,
    status       VARCHAR(20)    NOT NULL,
    created_at   TIMESTAMP(6)   NOT NULL,
    CONSTRAINT pk_price_alerts PRIMARY KEY (id),
    CONSTRAINT fk_price_alerts_portfolio_id FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT fk_price_alerts_asset_id FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE RESTRICT,
    CONSTRAINT ck_price_alerts_condition CHECK (condition IN ('PRICE_ABOVE', 'PRICE_BELOW')),
    CONSTRAINT ck_price_alerts_status CHECK (status IN ('PENDING', 'TRIGGERED', 'NOTIFIED', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT ck_price_alerts_target_price CHECK (target_price > 0)
);
-- scheduler ค้น alert ที่ status = 'PENDING' ทุกรอบ
CREATE INDEX IF NOT EXISTS idx_price_alerts_status ON price_alerts (status);
CREATE INDEX IF NOT EXISTS idx_price_alerts_portfolio_id ON price_alerts (portfolio_id);
CREATE INDEX IF NOT EXISTS idx_price_alerts_asset_id ON price_alerts (asset_id);

-- ---------- allocation_targets : สัดส่วนเป้าหมายต่อสินทรัพย์ในพอร์ต ----------
CREATE TABLE IF NOT EXISTS allocation_targets (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id   BIGINT        NOT NULL,
    asset_id       BIGINT        NOT NULL,
    target_percent NUMERIC(5, 2) NOT NULL,
    CONSTRAINT pk_allocation_targets PRIMARY KEY (id),
    CONSTRAINT uq_allocation_targets_portfolio_asset UNIQUE (portfolio_id, asset_id),
    CONSTRAINT fk_allocation_targets_portfolio_id FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT fk_allocation_targets_asset_id FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE RESTRICT,
    CONSTRAINT ck_allocation_targets_percent CHECK (target_percent BETWEEN 0 AND 100)
);
CREATE INDEX IF NOT EXISTS idx_allocation_targets_asset_id ON allocation_targets (asset_id);

-- ---------- rebalance_logs : ประวัติการรีบาลานซ์ (N:1 กับ portfolios) ----------
CREATE TABLE IF NOT EXISTS rebalance_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id BIGINT       NOT NULL,
    method       VARCHAR(20)  NOT NULL,
    triggered_at TIMESTAMP(6) NOT NULL,
    details      TEXT,
    CONSTRAINT pk_rebalance_logs PRIMARY KEY (id),
    CONSTRAINT fk_rebalance_logs_portfolio_id FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT ck_rebalance_logs_method CHECK (method IN ('THRESHOLD', 'CALENDAR'))
);
CREATE INDEX IF NOT EXISTS idx_rebalance_logs_portfolio_id ON rebalance_logs (portfolio_id, triggered_at);

-- ---------- user_watchlist : รายการหุ้นที่ผู้ใช้ติดตาม (ตารางเชื่อม N:M users <-> assets แบบไม่มีข้อมูลเพิ่ม) ----------
CREATE TABLE IF NOT EXISTS user_watchlist (
    user_id  BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    CONSTRAINT pk_user_watchlist PRIMARY KEY (user_id, asset_id),
    CONSTRAINT fk_user_watchlist_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    -- รายการติดตามเป็นแค่ที่คั่นหน้า ถ้าสินทรัพย์ถูกลบ ให้หายจาก watchlist ไปด้วย
    CONSTRAINT fk_user_watchlist_asset_id FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE
);
-- PK (user_id, asset_id) ค้นตาม user ได้แล้ว เพิ่ม index ฝั่ง asset สำหรับตรวจ FK ตอนลบสินทรัพย์
CREATE INDEX IF NOT EXISTS idx_user_watchlist_asset_id ON user_watchlist (asset_id);
